export const TEXTS = {
  errors: {
    title: 'Oops, something went wrong',
    default: 'Failed to load data',
    network: 'Network connection issues',
    timeout: 'Server is taking too long to respond',
    notFound: 'Data not found',
    server: 'Server error occurred',
  },
  buttons: {
    retry: '🔄 Try again',
    loadMore: 'Load More',
    featuresTab: 'Features',
    reviewsTab: 'Reviews',
    viewNow: 'View Now',
    showMore: 'Show more',
    search: 'Search',
    searching: 'Searching...',
    resetFilters: 'Reset filters',
    send: 'Send',
  },
  loading: {
    initial: 'Loading campers...',
    more: 'Loading more...',
  },
  homePage: {
    hero: {
      title: 'Campers of your dreams',
      subtitle: 'You can find everything you want in our catalog',
    },
  },
  header: {
    logoMain: 'Travel',
    logoSecondary: 'Trucks',
    home: 'Home',
    catalog: 'Catalog',
  },
  catalog: {
    title: 'Camper Catalog',
    allLoaded: 'All campers loaded!',
    searchingCampers: 'Searching campers...',
    foundResults: 'Found {count} camper{plural}',
    noMatchingCampers: 'No campers match your filters. Try adjusting your search criteria.',
    noCampersFound: 'No campers found',
    allFilteredLoaded: 'All {count} filtered camper{plural} loaded!',
  },
  filter: {
    location: '📍 {location}',
    form: '🚐 {form}',
    equipment: '✓ {equipment}',
    transmission: '⚙️ {transmission}',
  },
  filterSidebar: {
    locationLabel: 'Location',
    filtersTitle: 'Filters',
    vehicleEquipment: 'Vehicle equipment',
    vehicleType: 'Vehicle type',
    locationPlaceholder: 'City, Country',
  },
  bookingForm: {
    title: 'Book your campervan now',
    subtitle: 'Stay connected! We are always ready to help you.',
    namePlaceholder: 'Name*',
    emailPlaceholder: 'Email*',
    datePlaceholder: 'Booking date*',
    commentPlaceholder: 'Comment',
  },
  camperCard: {
    addToFavorites: 'Add to favorites',
    removeFromFavorites: 'Remove from favorites',
  },
  camper: {
    rating: 'Rating',
    tabs: {
      features: 'Features',
      reviews: 'Reviews',
    },
    vehicle: {
      title: 'Vehicle details',
      form: 'Form',
      length: 'Length',
      width: 'Width',
      height: 'Height',
      tank: 'Tank',
      consumption: 'Consumption',
    },
  },
  camperDetails: {
    reviews: '({count} Reviews)',
  },
  symbols: {
    heartFilled: '❤️',
    heartEmpty: '🤍',
    star: '⭐',
  } as const,
};
